<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Stateless" Version="5.15.0" />
    <PackageReference Include="JsonSchema.Net" Version="7.3.4" />
  </ItemGroup>
</Project>
